# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_worker', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('localization_x', models.FloatField()),
                ('localization_y', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searching.Account')),
            ],
        ),
    ]
